language: c

env:
  - LUASUFFIX=5.1 LUAVER=5.1
  - LUASUFFIX=5.2 LUAVER=5.2
  - LUASUFFIX=jit LUAVER=5.1

# Tool setup.
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq uuid-dev
  - bash tools/setup_system.sh

# Build and test.
script:
  - ./premake5 --to=build --lua-dir=${TRAVIS_BUILD_DIR}/lua/src gmake
  - cd build
  - make
  - cd ../test
  - busted --coverage

after_success:
  - luacov-coveralls

branches:
  only:
    - master

